# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Costa Rica Entertainment Group
email: gpacheco@cr-eg.com
description: "Costa Rica Entertainment Group es una empresa dedicada a la creación, desarrollo, difusión, promoción y comercialización de contenido dirigido al entretenimiento y la creación de experiencias."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://creg.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Collections
collections:
  eventos:
    output: true
    permalink: /eventos/:path/

#Gallery
gallery:
  # path to the gallery
  dir: photos
  # title for gallery index
  title: "Photos"
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: "Photos: "
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "date_time"
  # sizes for thumbnails
  thumbnail_size:
    x: 400
    y: 400

gems:
  - jekyll-gallery-generator